POST http://localhost:7500/auth/signup
Content-Type: application/json

{
    "email": "hello@email.com",
    "password": "87687dsfsdf678g67vyjgvuyvg"
}

### Find all users with email

GET http://localhost:7500/auth?email=hello@email.com

### Find a user

GET http://localhost:7500/auth/3

### Delete a user

DELETE http://localhost:7500/auth/delete/2

### Update a user

PATCH http://localhost:7500/auth/update/2
Content-Type: application/json

{
    "password": "helloThere!"
}